---
version: '3.9'

services:
  iperf:
    image: mlabbe/iperf3:${IPERF_TAG}
    healthcheck:
      disable: true
    labels:
      traefik.enable: true
      traefik.tcp.routers.iperftcp.entrypoints: iperftcp
      traefik.tcp.routers.iperftcp.rule: HostSNI(`*`)
      traefik.tcp.routers.iperftcp.service: iperftcp
      traefik.tcp.routers.iperftcp.tls: false
      traefik.tcp.routers.iperftcp.tls.passthrough: true
      traefik.tcp.services.iperftcp.loadbalancer.server.port: 5201
      traefik.udp.routers.iperfudp.entrypoints: iperfudp
      traefik.udp.routers.iperfudp.service: iperfudp
      traefik.udp.services.iperfudp.loadbalancer.server.port: 5201
    networks:
      - traefik
    restart: unless-stopped
networks:
  traefik:
    external: true
